### ISSUE TITLE
primus.forward shouldn't answer with error for empty servers list

### ISSUE THREAD

**Issue by raulmt** [primus/omega-supreme#19]
primus/metroplex adds the `broadcast` function to `primus.forward`, which just gathers all servers in the metroplex registry and calls `primus.forward`. But there is a problem when you want to boradcast and the only server available is the current one processing the `forward.broadcast` call: `metroplex.servers` will return empty list (since it ignores current server) and it will call `forward` with an empty list.

The problem is even when `forward` will do everything you would expect (passing the message to every spark on the current server) it will still [call the callback with an error saying "No servers provided"](https://github.com/primus/omega-supreme/blob/master/supreme.js#L119). So the `broadcast` will also fail, even considering the scenario is not something unusual (a cluster of current size 1, maybe because you don't need too much servers at the moment or you want a cluster setup in case you need to add more nodes).

At first I thought this should be primus/metroplex 's problem, but looking at the code there is not much you can do there… if you don't call `forward` you won't deliver the message to the sparks on the current server, and you won't have the stats you need to answer with. And if you do add the current server to the servers provided to `forward`, then for a broadcast type of message it will still call the current server even when all messages were locally delivered.

So, the only solution I can think of is to not answer with error in `primus.forward` for empty servers list. It kind of makes sense to me for the fact this function will always try to deliver to local sparks… so having empty servers list is like saying "please forward to local clients". An alternative would be to have a special parameter or another function that will allow you to only deliver to local sparks, so in metroplex you can call it instead of forward if you see there are no other servers but this one (although I think it's better to just support empty servers list because of the job done in `forward`).

Does this make sense? I can submit a PR if it does, but I would like some advice on the best solution to this unexpected error.

**Comment by fadeenk** [comment]
I was able to replicate and confirm the error. 

However, I suggest fixing that error on metroplex's end (since that is where the call is originating from). The reason for that is because `primus` has the ability to broadcast to all clients native-ly, no need to pass the info to another library to do that logic. We can just modify the logic prior to the [forward function call](https://github.com/primus/metroplex/blob/master/omega.js#L38) to have a check if the servers list is an empty array then do a self broadcast using primus directly like in [here](https://github.com/primus/omega-supreme/blob/master/omega.js#L149)

The other solution is to just add a case in [this if statement](https://github.com/primus/omega-supreme/blob/master/supreme.js#L113) for when broadcasting locally with no sparks.

Note: those suggestions are based on a quick look, not on an in depth understanding of both libraries. @lpinca would have a better understanding and clearer answer.

**Comment by lpinca** [comment]
Thanks for the detailed report.

> So, the only solution I can think of is to not answer with error in primus.forward for empty servers list. It kind of makes sense to me for the fact this function will always try to deliver to local sparks… so having empty servers list is like saying "please forward to local clients".

The error if the list is empty has to stay. Imagine something like this:

```js
primus.forward([], 'foo', ['ad8a-280z-18', 'y97x-42480-13'], fn);
```

where both of the sparks are not local. In that case there is not enough info as we don't know where those sparks are so an error is returned.

Both of the solution proposed by @fadeenk make sense and I agree that the issue should probably be fixed in metroplex where the issue originates.

Thanks.

**Comment by raulmt** [comment]
Thanks @fadeenk and @lpinca !

The reason why I think this shouldn't be fixed in metroplex's side is because it currently just delegates to `forward`, returning whatever it returns. If we do a self broadcast in metroplex's side, we would need to also build similar/compatible response than the one currently built in omega-supreme side, and keeping that up to date with any change made in omega-supreme (like adding sparks besides ok, send and local properties, for example).

If I understood @fadeenk correctly about the second approach, we would be giving `forward` the semantic of "broadcast to local sparks" when no sparks and no servers are given, right? I think that would make sense because, when you give sparks, even without any server, you still get a success response, so "no sparks + no servers" => "local broadcasting" would be a similar case.

I agree with your point @lpinca about not just removing the error for the case you mentioned, but this approach would only remove the error for the case when no servers *and* no sparks are given. What do you think? If you both are ok, I can send a PR for this.

**Comment by lpinca** [comment]
> but this approach would only remove the error for the case when no servers and no sparks are given.

I think this makes sense.
